# ---- Base Node ----
FROM node:lts AS base

### Optional: Set Proxy Variables
# ENV http_proxy {value}
# ENV https_proxy {value}
# ENV HTTP_PROXY {value}
# ENV HTTPS_PROXY {value}
# ENV no_proxy {value}
# ENV NO_PROXY {value}

WORKDIR /app
COPY . .

RUN npm set progress=false && npm config set depth 0
RUN npm install --production
RUN cp -R node_modules prod_node_modules
RUN npm install
RUN npm run lint && npm run build && npm test

# ---- Release ----
FROM node:lts-alpine AS release

### install azure cli
RUN \
  apk add --no-cache curl tar openssl sudo bash jq python3 && \
  apk add --virtual=build gcc libffi-dev musl-dev openssl-dev make python3-dev && \
  pip3 --no-cache-dir install --upgrade pip && \
  pip3 --no-cache-dir install azure-cli

RUN mkdir -p /root/.azure

EXPOSE 4120
WORKDIR /app

COPY --from=base /app/package.json .
COPY --from=base /app/prod_node_modules ./node_modules
COPY --from=base /app/dist ./dist
COPY --from=base /app/swagger/swagger.json ./swagger/swagger.json
