name: Docker Image Build

on:
  push:
    branches:
      - master

    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - 'README.md'
      - 'savenv.sh'

    tags:
      - v*


jobs:

  docker-build-push:

    runs-on: ubuntu-latest
    env:
      #  DOCKER_REPO  - the docker repository name in the form: organization/repository
      DOCKER_REPO: 'retaildevcrew/helium-typescript'

    steps:
    - uses: actions/checkout@v1

    - name: Login to registry
      run: |
        # Login to registry

        #    You must add the following secrets to github
        #    DOCKER_USER  - your dockerhub user name
        #    DOCKER_PAT   - the personal access token for dockerhub
       

        ## login to dockerhub
        echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Build Container
      run: docker build . --file Dockerfile --tag image

    - name: Docker Push
      run: |
        # Tag and push the docker image

        IMAGE_ID=$DOCKER_REPO

        # Tag image based on repo tag if a github label
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]
        then

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
          # Strip "v" prefix from tag name
          VERSION=$(echo $VERSION | sed -e 's/^v//')

          # tag the image with :beta, :Version and :stable
          docker tag image $IMAGE_ID:beta 
          docker tag image $IMAGE_ID:$VERSION
          docker tag image $IMAGE_ID:stable

        else
          # tag the image with :beta only if no tag
          docker tag image $IMAGE_ID:beta
        fi

        # Push to the repo
        docker push $IMAGE_ID

  acr-build-push-version:
    runs-on: ubuntu-latest
    env:
      ACR_REG: 'heliume2e'
      ACR_REPO: 'heliume2e.azurecr.io'
      ACR_IMAGE: 'helium-typescript'
      ACR_TAG: 'stable'
    steps:
      - uses: actions/checkout@v1
      - name: acr-push-build
        run: |
          #    You must add the following secrets to github
          #    SERVICE_PRINCIPAL  - your SP Client ID that has ACR Push IAM role
          #    SERVICE_PRINCIPAL_PASSWORD   - the personal access token for the SP Client id
          #    TENANT  - The tenant ID of the subscription of the ACR


          echo "Building Docker image ${ACR_REPO}/${ACR_IMAGE} from ${GITHUB_REPOSITORY} on ${{ github.ref }}; and pushing it to ${ACR_REG} Azure Container Registry"
          az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL }} -p ${{ secrets.SERVICE_PRINCIPAL_SECRET }} --tenant ${{ secrets.TENANT }}
          
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]
          then

          # Strip git ref prefix from version
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
          # Strip "v" prefix from tag name
            VERSION=$(echo $VERSION | sed -e 's/^v//')

            az acr build -r ${ACR_REG} -f Dockerfile -t ${ACR_REPO}/${ACR_IMAGE}:${VERSION} -t ${ACR_REPO}/${ACR_IMAGE}:${ACR_TAG} -t ${ACR_REPO}/${ACR_IMAGE}:beta https://github.com/${GITHUB_REPOSITORY}.git#${{ github.ref }}
          else
            az acr build -r ${ACR_REG} -f Dockerfile -t ${ACR_REPO}/${ACR_IMAGE}:beta https://github.com/${GITHUB_REPOSITORY}.git#${{ github.ref }}
          fi

  
