name: Move new issues into Triage

on: [issues]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:latest
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_PAT_AUTO }}
        GITHUB_PROJECT_URL: https://github.com/orgs/retaildevcrews/projects/1
        GITHUB_PROJECT_COLUMN_NAME: Triage
        DEBUG: true